### ISSUE TITLE
Lastest version not finding exams on CDs

### ISSUE THREAD

**Issue by doc-jay** [DraconPern/dovo#2]
this version isn't finding exams on CDs as much as it did in prior version.  This version just seems to be not reading dicomdir possibly?  Anything I can do to help troubleshoot?

**Comment by DraconPern** [comment]
Do you remember if it was v1.0.7 or if it was an earlier version that worked better?  If you can test older versions, that'll help quite a bit that way I can zero in on the change.

**Comment by DraconPern** [comment]
Also, which platform are you using dovo on?

**Comment by doc-jay** [comment]
sorry so late with my reply.  It was v1.06 that I thought worked best.  I am using this on Win7 x64.

**Comment by DraconPern** [comment]
Can you see if this one finds more, https://github.com/DraconPern/dovo/releases/tag/v1.0.9

**Comment by doc-jay** [comment]
yeah, this works as expected now with 1.0.9.  How do you propose to handle CDs that are 'encrypted' with a password?

**Comment by DraconPern** [comment]
Good to hear!  Can you open another issue request with some detail about these 'encrypted' CD? Thanks!
