### ISSUE TITLE
rip dicom from CDs with password

### ISSUE THREAD

**Issue by doc-jay** [DraconPern/dovo#3]
I was wondering if it could be possible to rip the dicom off of CDs that require a password first?  usually, its always the DOB of the patient, as in YYYYMMDD.

**Comment by DraconPern** [comment]
Any idea of the software or vendor that made the CD?  Hopefully the DICOM files are using standard encryption.

**Comment by doc-jay** [comment]
I do know that that the 'Veterans Hospital" (VA) encrypts every single CD they create.  I would think its standard encryption, but I also think they have developed their own software in house.

**Comment by boskar** [comment]
I've seen a few with a single zip-file containing all dicom with standard zip encryption.
