### ISSUE TITLE
dcmtk git is not accessible

### ISSUE THREAD

**Issue by marcheschi** [DraconPern/dovo#6]
Hi
First of all thank you for this useful software !!

Using the build.sh, I find that is impossible to download from the dcmtk git repository,
instead if I substitute it with the github url it runs fine.
 git clone https://github.com/DCMTK/dcmtk.git

Thank you
Paolo

**Comment by DraconPern** [comment]
Hmm strange!  I'll change it to GitHub, it's probably faster anyways.

**Comment by DraconPern** [comment]
Closed by commit 0048d08eab49c05bec858dcc3184e3cab2202402
