### ISSUE TITLE
Especial Characters Dovo

### ISSUE THREAD

**Issue by ivancecoel** [DraconPern/dovo#9]
Hello, first of all, thank you so much for your Dovo Software, works great.
I contact you because we have a little problem, I'm from spain and there are patient with the Ñ character in te patient name info, and if there are this character (Ñ), dovo doesn't show the images and we can't no import to Pacs, it's possible to fix this issue? I think is a language problem only.

**Comment by DraconPern** [comment]
I'll take a look.  If you can, can you tell me what the character set (0008,0005) field is in the dicom file? 

This tool can do it, or you can use dcmdump from the dcmtk toolkit.
https://rawgit.com/cornerstonejs/dicomParser/master/examples/dumpWithDataDictionary/index.html

It should be one of these  https://dcm4chee-arc-cs.readthedocs.io/en/latest/charsets.html

**Comment by DraconPern** [comment]
This has been fixed.
